// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhmupefawbimjqfuwjmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxobXVwZWZhd2JpbWpxZnV3am13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NDc4NTMsImV4cCI6MjA1NzAyMzg1M30.x7-GRGxUSI7I50IzAyF-EHZvPyHVoZqMWtjZlVx39Ns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);